//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alexa_API
{
    using System;
    using System.Collections.Generic;

    public class Customer
    {
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone_number { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Balance { get; set; }
        public string Account_number { get; set; }
        public string ImagePath { get; set; }
        public string Gender { get; set; }
        public string BirthDate { get; set; }
        public int ID { get; set; }
    }
}
